### PR TITLE
Dimension Data - Added cleanServer call to NetworkDomainTearDown

### PR DESCRIPTION
**Pull request by trevorflanagan**

### CODE REVIEW

**Comment by andreaturli** [comment]
lgtm

**Comment by trevorflanagan** [comment]
Thanks for taking a look @andreaturli

**Comment by demobox** [comment]
Thanks for the improvement, @trevorflanagan! Also looks good to me.

**Comment by nacx** [comment]
Merged to master as [748058c3](http://git-wip-us.apache.org/repos/asf/jclouds-examples/commit/748058c3).

**Pull request closed without merging**
