### PR TITLE
2.1.0

### PR DESCRIPTION
**Pull request by andreaturli**
based on discussion at https://github.com/jclouds/jclouds-examples/pull/88

--- 

I think next step would be to get rid of `jclouds.version` as you may end up having multiple jclouds versions on `jclouds-examples` classpath

Also, I think we should make a decision on the following modules:
```
    <module>blobstore-hdfs</module>
    <module>blobstore-karaf-shell</module>
    <module>camel-notifications</module>
    <module>cloudwatch-basics</module>
    <module>ec2-computeservice-spot</module>
    <module>ec2-createlamp</module>
    <module>ec2-windows</module>
    <module>minecraft-compute</module>
```
as at the moment they are not built

### CODE REVIEW

**Comment by gaul** [comment]
:+1: to this and removing the dead modules in a subsequent commit.

**Comment by demobox** [comment]
> fix README.md
> clean up pom.xml

Thanks for adding those changes, Andrea. Looks good to me!

**Comment by andreaturli** [comment]
thanks guys, merging now

**Comment by andreaturli** [comment]
merged at [master](https://git1-us-west.apache.org/repos/asf?p=jclouds-examples.git;a=commit;h=0168a3998effd336f610dd8261ae8f6fb09af2fd)

**Pull request closed without merging**
