### PR TITLE
Update google example for 1.9.0

### PR DESCRIPTION
**Pull request by stuarthendren**
Changes default ZONE to europe-west1-b as a no longer exists.
Changes the getHardware due to changes in id format.
Exposes more variable throught the system properties.

### CODE REVIEW

**Comment by nacx** [comment]
Please, keep the previous formatting (and indentation) so the diff only shows the actual changes.

**Comment by stuarthendren** [comment]
Do you have an eclipse formatter for the jclouds projects - or guidelines?

**Comment by stuarthendren** [comment]
I've changed the formatting to 3 spaces and line length 120.
Not sure if there are any other rules you use.

**Comment by andrewgaul** [comment]
Corrected typos in commit message, rebased, and pushed to master as cbe03d7108c4ef037efc396f9f45c864e21f5483.

**Pull request closed without merging**
