### PR TITLE
remove old google example

### PR DESCRIPTION
**Pull request by danbroudy**
I propose we remove the older google example because it is more difficult to run

### CODE REVIEW

**Comment by nacx** [comment]
I understand that the compute-basics is a better way to get started with GCE and see the compute service in action?

**Comment by danbroudy** [comment]
I think so. WDYT?

**Comment by nacx** [comment]
+1 The more providers we have properly working well with the compute basics the better. Thx!

**Comment by nacx** [comment]
Pushed to [master](http://git-wip-us.apache.org/repos/asf/jclouds-examples/commit/f3260f59). I added a note on the commit message explaining the motivation of the removal. Thx again!

**Pull request closed without merging**
