### PR TITLE
Adding License file and fixing compute-basic for GCE

### PR DESCRIPTION
**Pull request by danbroudy**
[JCLOUDS-859](https://issues.apache.org/jira/browse/JCLOUDS-859) causes ssh to fail when running the compute-basic example with google-compute-engine.

It makes sense for google to default to using OsFamily.DEBIAN to show minimal code changes between providers.

### CODE REVIEW

**Comment by demobox** [comment]
I don't think there are any issues with adding the license, but I'm not sure we _need_ it? jclouds-examples is not part of the jclouds distribution.

@abayer @ccustine: Some expert ASF advice would be appreciated ;-)

**Comment by nacx** [comment]
It is not needed, as we're not distributing it, but I see no problem in having the file in the repo. Even if not an ASF release, people downloading the tarball from GitHub will already have the license file, and that's not bad (we already have the license headers in all files, so it makes sense to have the license too).

I'd only change the file to be in plain text instead of markdown and rename it to `LICENSE` (upper case), to match the general conventions for this file. Apart from that, the change lgtm. Thanks @danbroudy!

**Comment by danbroudy** [comment]
updated!

**Comment by nacx** [comment]
Merged. Thanks @danbroudy!

**Pull request closed without merging**
